image: Visual Studio 2017

version: 18.2.0.{build}

configuration: Release

environment:
  release_zip: teamscale-profiler-dotnet_v$(appveyor_build_version).zip

before_build:
  - nuget restore

build_script:
  - msbuild Cqse.Teamscale.Profiler.Dotnet.sln /p:Platform=Win32 /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll"
  - msbuild Cqse.Teamscale.Profiler.Dotnet.sln /p:Platform=x64 /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll"

test_script:
  - ps: $results = (Resolve-Path . ).Path + "test_results.xml"
  - ps: dotnet test Profiler_Test/Profiler_Test.csproj -c $env:Configuration --no-build --no-restore --logger="trx;LogFileName=$results"
  - ps: $wc = New-Object System.Net.WebClient
  - ps: $wc.UploadFile("https://ci.appveyor.com/api/testresults/mstest/$($env:APPVEYOR_JOB_ID)", $results)

after_test:
  # Convert GitHub Wiki to PDF
  - git clone --depth=5 https://github.com/cqse/teamscale-profiler-dotnet.wiki.git wiki
  - npm install -g github-wikito-converter
  - curl -L https://github.com/wkhtmltopdf/wkhtmltopdf/releases/download/0.12.4/wkhtmltox-0.12.4_msvc2015-win64.exe --output wkhtmltox.exe
  - wkhtmltox.exe /S /D=C:\wkhtmltox
  - set PATH=%PATH%;C:\wkhtmltox\bin
  - sc start spooler # ensure the printer service is running for generating the PDF
  - wkhtmltopdf -V
  - gwtc -v --css wiki/export.css -t "Teamscale Ephemeral .NET Profiler" -f pdf wiki
  # Create release zip with profiler & documentation
  - 7z a %release_zip% .\Profiler\bin\Release\*.dll documentation.pdf

artifacts:
  - path: $(release_zip)
    name: profiler

deploy:
  - provider: GitHub
    auth_token:
      secure: APo4+sBDiSmiOI6yPrKS/4o3gu8yHaldPd9fmusOHnmVK5p7cxRuLAni0xkvH9nM
    release: $(APPVEYOR_REPO_TAG_NAME)
    artifact: $(release_zip)
    description: Release v$(appveyor_build_version)
    draft: true
    prerelease: false
    on:
      branch: master
      appveyor_repo_tag: true 

# Enable RDP
init:
  - ps: iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
on_finish:
  - ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
